basic/urls.py
from django.contrib import admin
from django.urls import path

from basic import views
from django.contrib.auth import views as auth_views
app_name = 'basic'

urlpatterns = [
    path('', views.index, ),
    path('sign-up', views.signup, name='sign-up'),

    path('get-result/', views.get_view, name='get-result'),
]

websie/urls.py
from django.contrib import admin
from django.urls import path, include

from basic import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('basic.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login_form.html',), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

basic/models.py
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.utils.translation import gettext_lazy as _
from uuid import uuid4
# Create your models here.


class UserTemp(models.Model):
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    verification_token = models.UUIDField(default=uuid4)
    verified = models.BooleanField(default=False)
    pass

basic/forms.py
from django import forms

from basic import models

class FileForm(forms.Form):
    pdf_file = forms.FileField(widget=forms.FileInput)


class UserRegisterForm(forms.ModelForm):

    class Meta:
        model = models.User
        fields = ['username', 'first_name', 'last_name', 'email']

basic/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core import mail
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse

from basic import forms, models
import pytesseract
from pytesseract import image_to_string
from basic.functions import ConvertPage

# Create your views here.

pytesseract.pytesseract.tesseract_cmd = r"D:\Program Files (x86)\Tesseract-OCR\tesseract.exe"


def success(request,message=None):
    return render(request, 'messages/success.html')

def index(request):
    return render(request, 'index.html')

def signup(request):
    if request.method == 'POST':
        form = forms.UserRegisterForm(request.POST)
        if form.is_valid():
            user: models.User = form.save(commit=False)
            password = models.User.objects.make_random_password()
            user.set_password(password)
            user.save()
            mail.send_mail(
              'User Registeration',
              'Welcome to my site:\nUserName: '+user.username+'\nYour Password is: ' + password,
              settings.EMAIL_HOST_USER,
                [form.cleaned_data.get('email')],

            )

            return render(request,'messages/register_success.html')
        else:
            return render(request, 'register_form.html', {'form': form})
    elif request.method == 'GET':
        form = forms.UserRegisterForm()
        return render(request,'register_form.html', {'form': form})

@login_required()
def get_view(request):
    if request.method == 'GET':
        form = forms.FileForm()
        return render(request, 'form.html', {'form': form})
    if request.method == 'POST':
        form = forms.FileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['pdf_file']
            convertPageObj = ConvertPage(file)
            text = convertPageObj.get_result()
            each_line = text.split('\n\n')
            result = [(each_line[i], each_line[i + 1]) for i in range(0, len(each_line) - 1, 2)]
            return render(request, 'get_result.html', {'result': result})
        return render(request, 'form.html', {'form': form})

templates/display_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>


</body>
</html>

templates/form.html
{% extends 'index.html' %}

{% block content %}
<section class="progress-area gray-bg">
<div class="container">
<div class="row">
    <h2>Register</h2>
    <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
        {% load crispy_forms_filters %}
{{ form|crispy }}
        <div class="row">
          <button class="bttn-default wow fadeInUp" type="submit">Upload</button>
</div>
    </form>
    </div>
    </div>
</section>

{% endblock %}

templates/get_result.html
{% extends 'index.html' %}

{% block content %}
<section class="progress-area gray-bg">
<div class="container">
<div class="row">
    {% for each_line in result %}
    <b>
{{ each_line.0 }}
    </b>
    <br>
    {{ each_line.1 }}
    <br>
{% endfor %}
    </div>
    </div>
</section>

{% endblock %}

templates/index.html
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta name="author" content="Sumon Rahman">
    <meta name="description" content="">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Title -->
    <title>{% block title %}

    {% endblock %}</title>
    <!-- Place favicon.ico in the root directory -->
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="shortcut icon" type="image/ico" href="images/favicon.ico" />
    {% block head %}
    {% include 'static_css_files.html' %}
    <!-- Plugin-CSS -->
        {% load static %}
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% endblock %}
</head>

<body data-spy="scroll" data-target=".mainmenu-area">
    <!-- Preloader-content -->
    <div class="preloader">
        <span><i class="lnr lnr-sun"></i></span>
    </div>
    <!-- MainMenu-Area -->
    <nav class="mainmenu-area" data-spy="affix" data-offset-top="200">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary_menu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src="static/images/logo.png" style="height: 75px; margin: -9px;"alt="Logo"></a>
            </div>
            <div class="collapse navbar-collapse" id="primary_menu">
                <div class="right-button hidden-xs">
                    <a href="{% url 'basic:get-result' %}">Upload File</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}?next=/">Logout</a>

                    {% else %}
                    <a href="{% url 'basic:sign-up' %}">Sign Up</a>
                    <a href="{% url 'login' %}?next=/">login</a>

                    {% endif %}
                {% if user.is_admin %}
                    <a href="{% url 'admin:auth_user_add' %}">Add User</a>
                {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <!-- MainMenu-Area-End -->
    <!-- Home-Area -->
    <header class="home-area overlay" id="home_page">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-6 ">
                    <h1 class="wow fadeInUp" data-wow-delay="0.4s">Welcome to WindQuo</h1>
                    <div class="space-20"></div>
                    <div class="desc wow fadeInUp" data-wow-delay="0.6s">
                        <p>Nations fastest platform to read window schedules.</p>
                    </div>
                    <div class="space-20"></div>
                </div>
                <div class="col-xs-12 hidden-sm col-md-5 col-md-offset-1">
                    <figure class="mobile-image wow fadeInUp" data-wow-delay="0.2s">
                        <img src="static/images/Window.png" alt="">
                    </figure>
                </div>
             </div>
            <div class="space-40 hidden-xs"></div>

            <div class="row">
                <div class="col-xs-6 col-md-3">
                    <div>
                        <h3 class="text-center">7-Day Trial</h3>
{#                        <p>London is the capital of England.</p>#}
                        <a href="#" class="bttn-white wow fadeInUp" data-wow-delay="0.8s"><i class=""></i>Free</a>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div>
                        <h3 class="text-center">Monthly Plan</h3>
{#                        <p>London is the capital of England.</p>#}
                        <a href="#" class="bttn-white wow fadeInUp" data-wow-delay="0.8s"><i class=""></i>Buy Now</a>
                    </div>
                </div>
            </div>
            <div class="space-80 hidden-xs"></div>
        </div>
    </header>
    <!-- Home-Area-End -->
    <!-- About-Area -->
    
    <!-- About-Area-End -->
    <!-- Progress-Area -->
    {% block content %}

    <section class="progress-area gray-bg" id="progress_page2">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-6">
                    <div class="page-title section-padding">
                        <h5 class="title wow fadeInUp" data-wow-delay="0.2s">Our Progress</h5>
                        <div class="space-10"></div>
                        <h3 class="dark-color wow fadeInUp" data-wow-delay="0.4s">Grat Application Ever</h3>
                        <div class="space-20"></div>
                        <div class="desc wow fadeInUp" data-wow-delay="0.6s">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiing elit, sed do eiusmod tempor incididunt ut labore et laborused sed do eiusmod tempor incididunt ut labore et laborused.</p>
                        </div>
                        <div class="space-50"></div>
                        <a href="#" class="bttn-default wow fadeInUp" data-wow-delay="0.8s">Learn More</a>
                    </div>
                </div>
                <div class="col-xs-12 col-md-5 col-md-offset-1">
                    <div class="page-title section-padding">
                        <img src="static/images/aprt.jpg" style="margin:30px; padding-right: 30px;"alt="">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="progress-area gray-bg" id="progress_page2">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-5">
                    <div class="page-title section-padding">
                        <img src="images/video-bg.jpg" alt="">
                    </div>
                </div>
                <div class="col-xs-12 col-md-6 col-md-offset-1">
                    <div class="page-title section-padding">
                        <h5 class="title wow fadeInUp" data-wow-delay="0.2s">Our Work</h5>
                        <div class="space-10"></div>
                        <h3 class="dark-color wow fadeInUp" data-wow-delay="0.4s">Grat Application Ever</h3>
                        <div class="space-20"></div>
                        <div class="desc wow fadeInUp" data-wow-delay="0.6s">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiing elit, sed do eiusmod tempor incididunt ut labore et laborused sed do eiusmod tempor incididunt ut labore et laborused.</p>
                        </div>
                        <div class="space-50"></div>
                        <a href="#" class="bttn-default wow fadeInUp" data-wow-delay="0.8s">Learn More</a>
                    </div>
                </div>
                
            </div>
        </div>
    </section>
    <!-- Progress-Area-End -->
    <!-- Video-Area -->
    {% endblock %}

    
    
    <!-- Subscribe-Form-Area -->
    <!-- Footer-Area -->
    <footer class="footer-area" id="contact_page">
        <div class="section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="page-title text-center">
                            <h5 class="title">Contact US</h5>
                            <h3 class="dark-color">Find Us By Bellow Details</h3>
                            <div class="space-60"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4">
                        <div class="footer-box">
                            <div class="box-icon">
                                <span class="lnr lnr-map-marker"></span>
                            </div>
                            <p>8-54 Paya Lebar Square <br /> 60 Paya Lebar Roa SG, Singapore</p>
                        </div>
                        <div class="space-30 hidden visible-xs"></div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="footer-box">
                            <div class="box-icon">
                                <span class="lnr lnr-phone-handset"></span>
                            </div>
                            <p>+65 93901336 <br /> +65 93901337</p>
                        </div>
                        <div class="space-30 hidden visible-xs"></div>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                        <div class="footer-box">
                            <div class="box-icon">
                                <span class="lnr lnr-envelope"></span>
                            </div>
                            <p>yourmail@gmail.com <br /> backpiper.com@gmail.com
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-Bootom -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-md-5">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            <span>Copyright All rights reserved | made 2020</span>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <div class="space-30 hidden visible-xs"></div>
                    </div>
                    <div class="col-xs-12 col-md-7">
                        <div class="footer-menu">
                            <ul>
                                <li><a href="#">About</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Features</a></li>
                                <li><a href="#">Pricing</a></li>
                                <li><a href="#">Testimonial</a></li>
                                <li><a href="#">Contacts</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-Bootom-End -->
    </footer>
    <!-- Footer-Area-End -->
    {% include 'static_script_files.html' %}
</body>

</html>

templates/login_form.html

{% block title %}
Login
{% endblock %}
{% block content %}
<section class="progress-area gray-bg">
<div class="container">
<div class="row">
    <h2>Login</h2>
    <form method="POST">
  {% csrf_token %}
        {% load crispy_forms_filters %}
{{ form|crispy }}
        <div class="row">
          <button class="bttn-default wow fadeInUp" type="submit">Login</button>
</div>
    </form>
    </div>
    </div>
</section>
{% endblock %}

templates/messages/base.html
{% extends 'index.html' %}

{% block content %}
Thanks For Coming Here
{% endblock %}

templates/messages/register_success.html
{% extends 'index.html' %}
{% block content %}

<section class="progress-area gray-bg">
<div class="container">
<div class="row">
You have Successfully Registered. Check your mail box for login and password.
</div>
</div>
</section>

{% endblock %}

templates/messages/success.html
{% extends 'index.html' %}

{% block content %}
You are Successfully Registered

{% endblock %}

templates/register_form.html
{% extends 'index.html' %}
{% block title %}
Register
{% endblock %}
{% block content %}
<section class="progress-area gray-bg">
<div class="container">
<div class="row">
    <h2>Register</h2>
    <form method="post">
  {% csrf_token %}
        {% load crispy_forms_filters %}
{{ form|crispy }}
        <div class="row">
          <button class="bttn-default wow fadeInUp" type="submit">Register</button>
</div>
    </form>
    </div>
    </div>
</section>
{% endblock %}

templates/static_css_files.html
{% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

templates/static_script_files.html
{% load static %}
    <!--Vendor-JS-->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-ui.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/contact-form.js' %}"></script>
    <script src="{% static 'js/ajaxchimp.js' %}"></script>
    <script src="{% static 'js/scrollUp.min.js' %}"></script>
    <script src="{% static 'js/magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>